environment:
  CYG_MIRROR: http://cygwin.mirror.constant.com
  FLAVOR: pharo.cog.spur
  matrix:
    - platform: x86
      ARCH: win32x86
      SRC_ARCH: i386
      CYG_ROOT: C:\cygwin
      CYG_SETUP: setup-x86.exe
      MINGW_ARCH: i686
#    - platform: x64
#      ARCH: win64x64
#      SRC_ARCH: x86_64
#      CYG_ROOT: C:\cygwin64
#      CYG_SETUP: setup-x86_64.exe
#      MINGW_ARCH: x86_64
matrix:
  fast_finish: false
clone_depth: 5
cache:
  - .thirdparty-cache
init:
  - git config --system core.longpaths true
#  - echo "Windows Original Path:"
#  - echo %PATH%
#  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%;%CYG_ROOT%\bin
install:
  - ps: 'Start-FileDownload "http://cygwin.com/setup-x86.exe" -FileName "setup-x86.exe"'
  - ps: 'Start-FileDownload "http://cygwin.com/setup-x86_64.exe" -FileName "setup-x86_64.exe"'
  - '%CYG_SETUP% -dgnqNO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_ROOT%\var\cache\setup" -P mingw64-%MINGW_ARCH%-gcc-core,mingw64-%MINGW_ARCH%-gcc-g++,mingw64-%MINGW_ARCH%-headers,mingw64-%MINGW_ARCH%-runtime,zip,mingw64-%MINGW_ARCH%-clang,libiconv-devel,libglib2.0-devel,perl,mingw64-%MINGW_ARCH%-zlib,cmake,mingw64-%MINGW_ARCH%-win-iconv'
build_script:
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/scripts; exec 0</dev/null; exec ./build-sources.sh -a i386"'
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/opensmalltalk-vm; exec 0</dev/null; export THIRDPARTYCACHEDIR=$APPVEYOR_BUILD_FOLDER/.thirdparty-cache; exec ./.travis_build.sh"'
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/scripts; exec 0</dev/null; exec ./pack-vm.sh"'
test_script:
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; exec ./scripts/run-tests.sh"'
before_deploy:
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/scripts; exec 0</dev/null; exec ./deploy-key.sh"'
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; exec ./scripts/deploy-key.sh"'
deploy_script:
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; exec ./scripts/deploy-bintray-appveyor.sh"'
  - '%CYG_ROOT%\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; exec ./scripts/deploy-files.pharo.org-appveyor.sh"'
